### ISSUE TITLE
Errors when compiling on Ubuntu 16.04

### ISSUE THREAD

**Issue by chriskretler** [darealshinji/vapoursynth-plugins#6]
Receiving the following error when running make:
make[1]: Entering directory '/home/vagrant/installs/vapoursynth-plugins/plugins/ctmf'
  CXX      src/CTMF_AVX2.o
  CXX      src/CTMF.o
  CXX      src/CTMF_SSE2.o
  CXX      src/vectorclass/instrset_detect.o
  CXXLD    ctmf.so
make[1]: Leaving directory '/home/vagrant/installs/vapoursynth-plugins/plugins/ctmf'
make -C plugins/d2vsource 
make[1]: Entering directory '/home/vagrant/installs/vapoursynth-plugins/plugins/d2vsource'
make -C ../.. -f ffmpeg.mak
make[2]: Entering directory '/home/vagrant/installs/vapoursynth-plugins'
CONFIGURE  ffmpeg
ffmpeg.mak:34: recipe for target 'ffmpeg/config.mak' failed
make[2]: *** [ffmpeg/config.mak] Error 1
make[2]: Leaving directory '/home/vagrant/installs/vapoursynth-plugins'
Makefile:19: recipe for target '../../ffmpeg_libs/lib/ffmpeg_stamp' failed
make[1]: *** [../../ffmpeg_libs/lib/ffmpeg_stamp] Error 2
make[1]: Leaving directory '/home/vagrant/installs/vapoursynth-plugins/plugins/d2vsource'
Makefile:22: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by darealshinji** [comment]
Looks like ffmpeg's configure script changed. I've updated `ffmpeg.mak`. Tip: run `make V=1` to get a more verbose output when such an error occurs.

**Comment by chriskretler** [comment]
Thanks for the tip!  That change got me past the first error.  I now see a build error later on.  Let me know if you'd prefer me to close this first issue and open a second:

make V=1 -C plugins/d2vsource 
make[1]: Entering directory '/home/vagrant/installs/vapoursynth-plugins/plugins/d2vsource'
make -f d2vsource.mak V=1
make[2]: Entering directory '/home/vagrant/installs/vapoursynth-plugins/plugins/d2vsource'
g++ -std=gnu++14 -c -Wall -Wextra -Wno-unused-parameter -Wno-unused-result -Werror=format-security -fPIC -fno-strict-aliasing -mfpmath=sse -msse2 -DVS_TARGET_CPU_X86 -D_FORTIFY_SOURCE=2 -Isrc -I../../include -I../../include/vapoursynth -Wno-sign-compare -I../../ffmpeg_libs/include -O3 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -o src/vapoursynth.o src/vapoursynth.cpp
In file included from src/applyrff.hpp:29:0,
                 from src/vapoursynth.cpp:31:
src/d2v.hpp:71:5: error: ‘FF_IDCT_XVIDMMX’ was not declared in this scope
     FF_IDCT_XVIDMMX,
     ^
../../cxx.inc:14: recipe for target 'src/vapoursynth.o' failed
make[2]: *** [src/vapoursynth.o] Error 1
make[2]: Leaving directory '/home/vagrant/installs/vapoursynth-plugins/plugins/d2vsource'
Makefile:16: recipe for target 'd2vsource.so' failed
make[1]: *** [d2vsource.so] Error 2
make[1]: Leaving directory '/home/vagrant/installs/vapoursynth-plugins/plugins/d2vsource'
Makefile:22: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by darealshinji** [comment]
I guess I should update the plugins, that may fix some issues. And maybe in future I should checkout the last working release branch of FFmpeg instead of master.

**Comment by chriskretler** [comment]
FWIW, I'm provisioning my dev environment via [this vagrant script](https://github.com/chriskretler/vsynth-env-provisioning/blob/master/vagrant-source/install-apps.sh).  I'm using ffmpeg 3.3.4.  I would be happy to help you test moving to an ffmpeg tag.

**Comment by darealshinji** [comment]
It builds with ffmpeg 3.4, so I've changed the autogen script to checkout the `release/3.4` branch.

**Comment by chriskretler** [comment]
Confirmed that it builds successfully.  Thank you for the quick attention.
